### ISSUE TITLE
actionPostPurge throw error

### ISSUE THREAD

**Issue by boydaihungst** [julianlam/nodebb-plugin-mentions#156]
I got error below when I try to purge a post or a topic with admin account
This is repo: https://github.com/boydaihungst/nodebb-mensions-error
Using this command to start  `docker-compose up --build`
```
error: TypeError: Cannot read properties of undefined (reading 'pid')
    at Object.Mentions.actionPostPurge [as method] (/usr/src/app/node_modules/nodebb-plugin-mentions/library.js:174:37)
    at Object.fireActionHook [as action] (/usr/src/app/src/plugins/hooks.js:184:18)
    at Hooks.fire (/usr/src/app/src/plugins/hooks.js:105:49)
    at Object.wrapperCallback [as fire] (/usr/src/app/src/promisify.js:46:11)
    at Posts.purge (/usr/src/app/src/posts/delete.js:67:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Topics.purgePostsAndTopic (/usr/src/app/src/topics/delete.js:68:3)
    at topicTools.purge (/usr/src/app/src/topics/tools.js:83:3)
    at /usr/src/app/src/api/helpers.js:66:16
```

**Comment by barisusakli** [comment]
@boydaihungst thanks for reporting, fixed in nodebb-plugin-mentions@3.0.3
