### ISSUE TITLE
TypeError: Cannot read property 'pid' of undefined in `actionPostPurge`

### ISSUE THREAD

**Issue by gwynnarth** [julianlam/nodebb-plugin-mentions#157]
Hello,

purging a post causes the following error to be thrown:

```
(node:99) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pid' of undefined
    at Object.Mentions.actionPostPurge [as method] (/home/app/nodebb/node_modules/nodebb-plugin-mentions/library.js:174:37)
    at Object.fireActionHook [as action] (/home/app/nodebb/src/plugins/hooks.js:184:18)
    at Hooks.fire (/home/app/nodebb/src/plugins/hooks.js:105:49)
    at Object.wrapperCallback [as fire] (/home/app/nodebb/src/promisify.js:46:11)
    at Posts.purge (/home/app/nodebb/src/posts/delete.js:67:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.postsAPI.purge (/home/app/nodebb/src/api/posts.js:172:2)
    at async Posts.purge (/home/app/nodebb/src/controllers/write/posts.js:28:2)
    at async /home/app/nodebb/src/routes/helpers.js:61:5
(Use `node --trace-warnings ...` to show where the warning was created)
(node:99) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:99) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Obviously the mentions objects (if they exist) are not deleted from a database either.

NodeBB version: 1.18.6
nodebb-plugin-mentions version: 3.0.2

Let me know if you need more info, but this is pretty straightforward to reproduce ;-)
Thanks!

**Comment by pitaj** [comment]
#156
