### ISSUE TITLE
Mentions causing NodeBB to crash when purging topic

### ISSUE THREAD

**Issue by gradiian** [julianlam/nodebb-plugin-mentions#163]
NodeBB version: 1.18.6
Plugin version: 3.0.2

When attempting to purge a topic, NodeBB crashes. It eventually does purge the topic on the third attempt. The topic was created by the admin account and included posts from a test moderator account. I deleted the topic as admin and purged as admin.

```
2021-12-13T14:38:46.360Z [4567/1818921] - [31merror[39m: uncaughtException: Cannot read properties of undefined (reading 'pid')
TypeError: Cannot read properties of undefined (reading 'pid')
    at Object.Mentions.actionPostPurge [as method] (/sites/community.lifehousefans.net/node_modules/nodebb-plugin-mentions/library.js:174:37)
    at Object.fireActionHook [as action] (/sites/community.lifehousefans.net/src/plugins/hooks.js:184:18)
    at Hooks.fire (/sites/community.lifehousefans.net/src/plugins/hooks.js:105:49)
    at Object.wrapperCallback [as fire] (/sites/community.lifehousefans.net/src/promisify.js:46:11)
    at Posts.purge (/sites/community.lifehousefans.net/src/posts/delete.js:67:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {"date":"Mon Dec 13 2021 14:38:46 GMT+0000 (Greenwich Mean Time)","error":{},"exception":true,"os":{"loadavg":[0.09,0.1,0.04],"uptime":847643.33},"process":{"argv":["/home/seggleston/.nvm/versions/node/v16.13.1/bin/node","/sites/community.lifehousefans.net/app.js"],"cwd":"/sites/community.lifehousefans.net","execPath":"/home/seggleston/.nvm/versions/node/v16.13.1/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":671422,"external":21003656,"heapTotal":139296768,"heapUsed":113802424,"rss":196395008},"pid":1818921,"uid":1000,"version":"v16.13.1"},"stack":"TypeError: Cannot read properties of undefined (reading 'pid')\n    at Object.Mentions.actionPostPurge [as method] (/sites/community.lifehousefans.net/node_modules/nodebb-plugin-mentions/library.js:174:37)\n    at Object.fireActionHook [as action] (/sites/community.lifehousefans.net/src/plugins/hooks.js:184:18)\n    at Hooks.fire (/sites/community.lifehousefans.net/src/plugins/hooks.js:105:49)\n    at Object.wrapperCallback [as fire] (/sites/community.lifehousefans.net/src/promisify.js:46:11)\n    at Posts.purge (/sites/community.lifehousefans.net/src/posts/delete.js:67:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","trace":[{"column":37,"file":"/sites/community.lifehousefans.net/node_modules/nodebb-plugin-mentions/library.js","function":"Object.Mentions.actionPostPurge [as method]","line":174,"method":"actionPostPurge [as method]","native":false},{"column":18,"file":"/sites/community.lifehousefans.net/src/plugins/hooks.js","function":"Object.fireActionHook [as action]","line":184,"method":"fireActionHook [as action]","native":false},{"column":49,"file":"/sites/community.lifehousefans.net/src/plugins/hooks.js","function":"Hooks.fire","line":105,"method":"fire","native":false},{"column":11,"file":"/sites/community.lifehousefans.net/src/promisify.js","function":"Object.wrapperCallback [as fire]","line":46,"method":"wrapperCallback [as fire]","native":false},{"column":17,"file":"/sites/community.lifehousefans.net/src/posts/delete.js","function":"Posts.purge","line":67,"method":"purge","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false}]}
2021-12-13T14:38:46.362Z [4567/1818921] - [31merror[39m: TypeError: Cannot read properties of undefined (reading 'pid')
    at Object.Mentions.actionPostPurge [as method] (/sites/community.lifehousefans.net/node_modules/nodebb-plugin-mentions/library.js:174:37)
    at Object.fireActionHook [as action] (/sites/community.lifehousefans.net/src/plugins/hooks.js:184:18)
    at Hooks.fire (/sites/community.lifehousefans.net/src/plugins/hooks.js:105:49)
    at Object.wrapperCallback [as fire] (/sites/community.lifehousefans.net/src/promisify.js:46:11)
```

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-mentions/issues/156
