### ISSUE TITLE
Console log prints "MongoError: skip requires an integer"

### ISSUE THREAD

**Issue by jujokini** [julianlam/nodebb-plugin-mentions#56]
I got error "MongoError: skip requires an integer" with this plugin on 0.7.x branch
    at Function.MongoError.create (/work/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at Cursor.skip (/work/node_modules/mongodb/lib/cursor.js:498:49)
    at getSortedSetRange (/work/src/database/mongo/sorted.js:130:5)
    at Object.module.getSortedSetRevRange (/work/src/database/mongo/sorted.js:108:3)
    at Object.Groups.getGroups (/work/src/groups.js:110:6)
    at SocketPlugins.mentions.listGroups (/work/node_modules/nodebb-plugin-mentions/library.js:222:9)
    at callMethod (/work/src/socket.io/index.js:204:2)
    at onMessage (/work/src/socket.io/index.js:149:3)
    at Socket.<anonymous> (/work/src/socket.io/index.js:61:3)
    at Socket.emit (events.js:107:17)

I looks like nodebb-plugin-mentions/library.js:222 is sending wrong parameters:
	Groups.getGroups('groups:visible:createtime', 0, -1, function(err, groups) {...
Expected at /src/groups.js:110
	Groups.getGroups = function(start, stop, callback) {...

**Comment by barisusakli** [comment]
Can you downgrade the plugin to 0.11.8.

**Comment by jujokini** [comment]
Thanks for the tip. NodeBB package.json on top level has  "nodebb-plugin-mentions": "^0.11.7" and this pulled 0.11.9 for me. I changed it to "nodebb-plugin-mentions": "0.11.8" and now it works.

**Comment by julianlam** [comment]
@barisusakli what's the nature of this bug? If it requires a newer version
of NodeBB, then it should be a major version, no?

**Comment by jujokini** [comment]
I did delete the "npm-shrinkwrap.json" file. This could have led to the situation where the bug occured.

**Comment by barisusakli** [comment]
@julianlam yeah I should have released a major version of this plugin instead of a minor increase.

**Comment by julianlam** [comment]
Will do. v0.11.9 no longer exists in npm, v1.0.0 only available for v0.7.3 (when it is released later today [probably])
